### PR TITLE
:tada: Add maplibre-gl-js-vue-amplify

### PR DESCRIPTION
**Pull request by dayjournal**
Hi, 
This example demonstrates how to use MapLibre GL JS with Amazon Location Service and AWS Amplify within a Vue.js application.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Hello @dayjournal, thank you for contributing to this sample repo. I was able to successfully test the sample but I was wondering if you'd be willing to remove the authentication part before merging since that part is out of the scope of a base map sample.

All the other JS samples allow consuming the map without the need to create an account and this makes the samples easier to test & removes additional complexity derived from the auth part.

Would that work for you?

**Comment by dayjournal** [comment]
@dreamorosi

Removed the login function.

**Comment by dayjournal** [comment]
@dreamorosi 

Hi, Can you please check the latest pull request?

**Comment by dreamorosi** [comment]
Was not able to run the sample with the latest changes (commit ):

Started from a fresh clone & checkout, steps to reproduce:
```bash
~/Codes 40s
❯ git clone git@github.com:dayjournal/amazon-location-samples.git als     
Cloning into 'als'...
remote: Enumerating objects: 1619, done.
remote: Counting objects: 100% (1103/1103), done.
remote: Compressing objects: 100% (702/702), done.
remote: Total 1619 (delta 591), reused 734 (delta 344), pack-reused 516
Receiving objects: 100% (1619/1619), 17.61 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (733/733), done.

~/Codes 16s
❯ cd als

~/Codes/als main
❯ git checkout feature/maplibre-gl-js-vue-amplify
Branch 'feature/maplibre-gl-js-vue-amplify' set up to track remote branch 'feature/maplibre-gl-js-vue-amplify' from 'origin'.
Switched to a new branch 'feature/maplibre-gl-js-vue-amplify'

~/Codes/als feature/maplibre-gl-js-vue-amplify
❯ cd maplibre-gl-js-vue-amplify 

~/Codes/als/maplibre-gl-js-vue-amplify feature/maplibre-gl-js-vue-amplify
❯ npm install
// Output removed for brevity
added 2103 packages, and audited 2103 packages in 31s

96 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (27 moderate, 11 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

~/Codes/als/maplibre-gl-js-vue-amplify feature/maplibre-gl-js-vue-amplify*
❯ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS access keys
? accessKeyId:  ********************
? secretAccessKey:  ****************************************
? region:  eu-west-1
Adding backend environment dev to AWS Amplify app: d31sakjaiyfbil
⠋ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-amplifygeo-dev-171624 AWS::CloudFormation::Stack Wed Dec 08 2021 17:16:28 GMT+0100 (Central European Standard Time) User Initiated             
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Wed Dec 08 2021 17:16:32 GMT+0100 (Central European Standard Time)                            
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Wed Dec 08 2021 17:16:32 GMT+0100 (Central European Standard Time)                            
CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Wed Dec 08 2021 17:16:32 GMT+0100 (Central European Standard Time)                            
CREATE_IN_PROGRESS UnauthRole                    AWS::IAM::Role             Wed Dec 08 2021 17:16:33 GMT+0100 (Central European Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                      AWS::IAM::Role             Wed Dec 08 2021 17:16:33 GMT+0100 (Central European Standard Time) Resource creation Initiated
CREATE_IN_PROGRESS DeploymentBucket              AWS::S3::Bucket            Wed Dec 08 2021 17:16:33 GMT+0100 (Central European Standard Time) Resource creation Initiated
⠼ Initializing project in the cloud...

CREATE_COMPLETE AuthRole   AWS::IAM::Role Wed Dec 08 2021 17:16:48 GMT+0100 (Central European Standard Time) 
CREATE_COMPLETE UnauthRole AWS::IAM::Role Wed Dec 08 2021 17:16:49 GMT+0100 (Central European Standard Time) 
⠼ Initializing project in the cloud...

CREATE_COMPLETE DeploymentBucket              AWS::S3::Bucket            Wed Dec 08 2021 17:16:55 GMT+0100 (Central European Standard Time) 
CREATE_COMPLETE amplify-amplifygeo-dev-171624 AWS::CloudFormation::Stack Wed Dec 08 2021 17:16:57 GMT+0100 (Central European Standard Time) 
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
✖ There was an error initializing your environment.
Error: File at path: '/Users/USER/Codes/als/maplibre-gl-js-vue-amplify/amplify/backend/auth/amplifygeod3677763/build/parameters.json' does not exist
    at Function.JSONUtilities.readJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)
    at StateManager.getData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)
    at StateManager.getResourceParametersJson (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:147:17)
    at ensureAmplifyMetaFrontendConfig (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)
    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)
    at initializeEnv (/usr/local/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:103:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at onSuccess (/usr/local/lib/node_modules/@aws-amplify/cli/src/init-steps/s9-onSuccess.ts:68:3)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/commands/init.ts:30:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:204:3)
    at executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```
Even though it errors out (like seen above) the Stack on CloudFormation was created successfully. I then tried to run `amplify push` and **I was able to deploy all the resources successfully & run the demo**.

I've tried a couple of times, with two different machines (my laptop & a Cloud9 instance) and I get the same error in both cases.

By looking at other samples in this repo - [like this one](https://github.com/aws-samples/amazon-location-samples/tree/main/maplibre-gl-js-react-amplify/amplify/backend) - we can see that the `amplify/backend` folder in your branch is missing some folders/files (see below for details) which seem to match with the error I'm getting above.

```bash
~/Codes/als/maplibre-gl-js-vue-amplify feature/maplibre-gl-js-vue-amplify*
❯ cp -R ../maplibre-gl-js-react-amplify/amplify .

~/Codes/als/maplibre-gl-js-vue-amplify feature/maplibre-gl-js-vue-amplify*
❯ git status
On branch feature/maplibre-gl-js-vue-amplify
Your branch is up to date with 'origin/feature/maplibre-gl-js-vue-amplify'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   amplify/.config/project-config.json
	deleted:    amplify/backend/auth/amplifygeod3677763/cli-inputs.json
	modified:   amplify/backend/backend-config.json
	deleted:    amplify/backend/geo/AmplifyGeoMapVue/AmplifyGeoMapVue-cloudformation-template.json
	deleted:    amplify/backend/geo/AmplifyGeoMapVue/parameters.json
	deleted:    amplify/backend/types/amplify-dependent-resources-ref.d.ts
	modified:   package-lock.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	amplify/backend/auth/maplibrereact022beae3/
	amplify/backend/geo/maplibrereact/

no changes added to commit (use "git add" and/or "git commit -a")
```

My recommendation in this case would be to do one of the following two actions:
- In your branch `rm -rf amplify` and then `cp -R ../maplibre-gl-js-react-amplify/amplify .` to copy the Amplify resources from another working sample (this would also make it uniform with the others) - tested this on my machine and was able to run your sample - the only difference is that this uses an Esri map while yours was using HERE.
- In your branch `rm -rf amplify` and then reinitialise the project (`amplify init` & `amplify add geo`) while also including the right files/folders to source.

Once this is fixed I'll be happy to approve & merge :)

**Review by dreamorosi — CHANGES_REQUESTED** [review]
See [comment above](https://github.com/aws-samples/amazon-location-samples/pull/80#issuecomment-988986191) for required changes. Thanks in advance.

**Comment by dayjournal** [comment]
@dreamorosi 

Thanks for the confirmation.
I replaced the Amplify file and confirmed that it started.

**Comment by dreamorosi** [comment]
Thank you, will review it later today (about ~10hrs from now) and then merge if  I can reproduce on my end.

**Comment by dayjournal** [comment]
Thank you for your support.

**Review by dreamorosi — APPROVED** [review]
🎉 Merging the branch 🎉 

Thanks a lot for contributing to this repo!

**Pull request merged**
